# k8s Config file for Persisten Volume due to bugfix lecture 223

apiVersion: v1
kind: PersistentVolume
metadata:
    name: database-persistent-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt"